İlk növbədə pandas kitabxanasını çağırırıq və csv faylımızı oxuyuruq

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Yaqub\Downloads\airlines_flights_data.csv")

DataFrame-ə baxaq

In [ ]:
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

Uçuş şirkətlərini olan sütuna nəzər yetirək

In [9]:
df['airline']

0         SpiceJet
1         SpiceJet
2          AirAsia
3          Vistara
4          Vistara
            ...
300148     Vistara
300149     Vistara
300150     Vistara
300151     Vistara
300152     Vistara
Name: airline, Length: 300153, dtype: str

Hər şirkətin tezliklərinin sayına baxaq

In [10]:
df['airline'].value_counts()

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

Hər şirkətin qazandığı məbləğin ortalamasını çıxarıb, onları azalan sıra ilə düzürük.Qiymətin aviaşirkətlərə görə dəyişdiyini əminliklə deyə bilərik.

In [41]:
df.groupby('airline')['price'].mean().sort_values(ascending=False)

airline
Vistara      30396.536302
Air_India    23507.019112
SpiceJet      6179.278881
GO_FIRST      5652.007595
Indigo        5324.216303
AirAsia       4091.072742
Name: price, dtype: float64

In [24]:
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [25]:
df.groupby(['airline','class'])['price'].mean()

airline    class
AirAsia    Economy      4091.072742
Air_India  Business    47131.039212
           Economy      7313.682169
GO_FIRST   Economy      5652.007595
Indigo     Economy      5324.216303
SpiceJet   Economy      6179.278881
Vistara    Business    55477.027777
           Economy      7806.943645
Name: price, dtype: float64

In [40]:
df.groupby(['departure_time','arrival_time'])['price'].mean().sort_values(ascending=False)

departure_time  arrival_time
Night           Evening          31425.824194
Early_Morning   Late_Night       29638.037500
Late_Night      Night            29439.811321
Evening         Morning          28326.216482
Night           Afternoon        28115.362126
Morning         Night            26827.897551
Afternoon       Morning          26056.580994
Early_Morning   Night            25792.007764
Night           Morning          25573.642137
Evening         Afternoon        25569.672277
Early_Morning   Evening          24804.077441
Evening         Evening          24612.547643
Morning         Late_Night       23624.505755
                Early_Morning    22625.786578
                Evening          21636.529952
Late_Night      Evening          21217.106383
Afternoon       Early_Morning    21159.511401
                Night            19097.798757
Late_Night      Afternoon        18520.684932
Evening         Early_Morning    18175.929529
Night           Night            17817.956009
Morning         Morning          17548.738563
Early_Morning   Afternoon        16564.731082
Evening         Night            15641.705242
Afternoon       Evening          15548.836651
                Afternoon        14741.746011
Morning         Afternoon        13271.433547
Early_Morning   Morning          12299.838792
Night           Early_Morning    12075.785461
Afternoon       Late_Night       10811.615662
Early_Morning   Early_Morning     9540.191523
Evening         Late_Night        8547.029235
Late_Night      Morning           7104.374684
Night           Late_Night        6590.831766
Late_Night      Early_Morning     4548.700599
                Late_Night        4288.291971
Name: price, dtype: float64

In [60]:
df.head(30)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954
10,10,GO_FIRST,G8-392,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954
11,11,GO_FIRST,G8-338,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5954
12,12,Indigo,6E-5001,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955
13,13,Indigo,6E-6202,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.17,1,5955
14,14,Indigo,6E-549,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5955
15,15,Indigo,6E-6278,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
16,16,Air_India,AI-887,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.08,1,5955
17,17,Air_India,AI-665,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955
18,18,AirAsia,I5-747,Delhi,Evening,one,Early_Morning,Mumbai,Economy,12.25,1,5949
19,19,AirAsia,I5-747,Delhi,Evening,one,Morning,Mumbai,Economy,16.33,1,5949
20,20,GO_FIRST,G8-266,Delhi,Early_Morning,one,Evening,Mumbai,Economy,11.75,1,5954
21,21,GO_FIRST,G8-101,Delhi,Early_Morning,one,Night,Mumbai,Economy,14.50,1,5954
22,22,GO_FIRST,G8-103,Delhi,Evening,one,Morning,Mumbai,Economy,15.67,1,5954
23,23,Air_India,AI-441,Delhi,Evening,one,Night,Mumbai,Economy,3.75,1,5955
24,24,Indigo,6E-5328,Delhi,Morning,zero,Morning,Mumbai,Economy,2.50,1,6165
25,25,Vistara,UK-933,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6690
26,26,Indigo,6E-2046,Delhi,Evening,zero,Evening,Mumbai,Economy,2.17,1,6585
27,27,AirAsia,I5-744,Delhi,Morning,one,Afternoon,Mumbai,Economy,5.83,1,8869
28,28,SpiceJet,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,10260
29,29,Indigo,6E-5041,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,10470

In [58]:
df.groupby(['source_city','destination_city'])['price'].mean().sort_values(ascending=True)

source_city  destination_city
Hyderabad    Delhi               17243.945685
Delhi        Hyderabad           17347.288379
Bangalore    Delhi               17723.313972
Delhi        Bangalore           17880.216315
Mumbai       Delhi               18725.320008
Chennai      Delhi               18981.863948
Delhi        Mumbai              19355.829812
             Chennai             19369.881354
Kolkata      Delhi               19422.354559
Hyderabad    Mumbai              20080.865759
Delhi        Kolkata             20566.409418
Hyderabad    Kolkata             20823.893201
Mumbai       Hyderabad           21004.046705
Bangalore    Hyderabad           21226.121192
Hyderabad    Bangalore           21347.177998
Kolkata      Hyderabad           21500.011397
Chennai      Hyderabad           21591.345404
Hyderabad    Chennai             21848.065989
Kolkata      Mumbai              22078.883579
Mumbai       Kolkata             22379.146723
Chennai      Kolkata             22669.932407
Kolkata      Bangalore           22744.808428
Chennai      Mumbai              22765.849647
Mumbai       Chennai             22781.899112
Bangalore    Mumbai              23128.618672
Mumbai       Bangalore           23147.873807
Bangalore    Chennai             23321.850078
             Kolkata             23500.061229
Kolkata      Chennai             23660.361040
Chennai      Bangalore           25081.850454
Name: price, dtype: float64

Uçuşa qalmış günlərə əsasən biletlərin satış qiymətlərini sıralayırıq.

In [11]:
df.groupby('days_left')['price'].mean().sort_values(ascending=False).head(15)

days_left
2     30211.299801
3     28976.083569
5     26679.773368
4     25730.905653
9     25726.246072
7     25588.367351
10    25572.819134
8     24895.883995
6     24856.493902
11    22990.656070
14    22678.002363
12    22505.803322
13    22498.885384
15    21952.540852
1     21591.867151
Name: price, dtype: float64

Maksimum qiymətləri analiz edək. Görürük ki, uçuşa az qalmış günlərin satışında bahalaşma görünür, amma bu linear(xətti) deyil.

In [14]:
df.groupby('days_left').agg({'price' : max}).head(10)

            price
days_left
1          116562
2          114523
3          123071
4          110936
5          117307
6          105961
7          105744
8          102114
9           98465
10         107934

In [15]:
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

Economy və business sinifə görə qiymət ortalaması arasında qat-qat fərqi görürük.

In [21]:
df.groupby(['class'])['price'].mean()

class
Business    52540.081124
Economy      6572.342383
Name: price, dtype: float64

In [26]:
df.groupby(['airline','class'])['price'].mean().unstack

<bound method Series.unstack of airline    class
AirAsia    Economy      4091.072742
Air_India  Business    47131.039212
           Economy      7313.682169
GO_FIRST   Economy      5652.007595
Indigo     Economy      5324.216303
SpiceJet   Economy      6179.278881
Vistara    Business    55477.027777
           Economy      7806.943645
Name: price, dtype: float64>

In [41]:
mean_of_duration = df['duration'].mean()
print(mean_of_duration.round(2))

12.22

In [3]:
df.groupby('class')['duration'].mean()

class
Business    13.704274
Economy     11.550060
Name: duration, dtype: float64

Durak saylarının ortalamalarının qiymətə necə təsir etdiyini görürük.

In [28]:
df.groupby('stops')['price'].mean().unstack

<bound method Series.unstack of stops
one            22900.992482
two_or_more    14113.450775
zero            9375.938535
Name: price, dtype: float64>

In [22]:
df.groupby('stops')['class'].value_counts().reset_index()

         stops     class   count
0          one   Economy  166561
1          one  Business   84302
2  two_or_more   Economy   12203
3  two_or_more  Business    1083
4         zero   Economy   27902
5         zero  Business    8102

In [45]:
df.groupby('stops')['duration'].agg('mean').sort_values(ascending=True).round(2)

stops
zero            2.19
one            13.50
two_or_more    15.32
Name: duration, dtype: float64

Qalmış günlərə əsasən qiymət paylanması edirik.

In [82]:
df['days_left']

0          1
1          1
2          1
3          1
4          1
          ..
300148    49
300149    49
300150    49
300151    49
300152    49
Name: days_left, Length: 300153, dtype: int64

In [76]:
df['days_group'] = pd.cut(df['days_left'], bins=[0,10,20,30,40,50], labels=['0-10','11-20','21-30','31-40','41-50'])

In [79]:
df.groupby('days_group')['days_left'].mean()

days_group
0-10      6.070715
11-20    15.523270
21-30    25.496287
31-40    35.502463
41-50    44.932581
Name: days_left, dtype: float64

In [69]:
df.sample(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,flight_type,days_group
51821,51821,AirAsia,I5-336,Mumbai,Night,one,Late_Night,Delhi,Economy,7.17,45,2336,Orta,41-50
256673,256673,Air_India,AI-501,Bangalore,Afternoon,one,Night,Hyderabad,Business,7.25,13,56476,Orta,11-20
26072,26072,Air_India,AI-540,Delhi,Night,one,Morning,Kolkata,Economy,12.92,35,4385,Orta,31-40
106033,106033,Indigo,6E-886,Bangalore,Morning,one,Evening,Kolkata,Economy,9.92,25,5021,Orta,21-30
102979,102979,Indigo,6E-6798,Bangalore,Afternoon,one,Evening,Kolkata,Economy,6.58,3,14796,Orta,0-10
12851,12851,GO_FIRST,G8-133,Delhi,Afternoon,one,Night,Bangalore,Economy,6.92,16,5610,Orta,11-20
93275,93275,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,13.33,46,4111,Orta,41-50
107525,107525,Indigo,6E-484,Bangalore,Early_Morning,one,Afternoon,Kolkata,Economy,6.17,35,4392,Orta,31-40
52355,52355,Vistara,UK-873,Mumbai,Early_Morning,one,Afternoon,Delhi,Economy,6.17,47,5547,Orta,41-50
273983,273983,Air_India,AI-768,Kolkata,Afternoon,one,Morning,Chennai,Business,17.42,32,55983,Uzun,31-40

In [85]:
df.head(30)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,flight_type,days_group
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,Qısa,0-10
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,Qısa,0-10
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,Qısa,0-10
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,Qısa,0-10
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,Qısa,0-10
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955,Qısa,0-10
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060,Qısa,0-10
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060,Qısa,0-10
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954,Qısa,0-10
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954,Qısa,0-10
10,10,GO_FIRST,G8-392,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954,Qısa,0-10
11,11,GO_FIRST,G8-338,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5954,Qısa,0-10
12,12,Indigo,6E-5001,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955,Qısa,0-10
13,13,Indigo,6E-6202,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.17,1,5955,Qısa,0-10
14,14,Indigo,6E-549,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5955,Qısa,0-10
15,15,Indigo,6E-6278,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,Qısa,0-10
16,16,Air_India,AI-887,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.08,1,5955,Qısa,0-10
17,17,Air_India,AI-665,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955,Qısa,0-10
18,18,AirAsia,I5-747,Delhi,Evening,one,Early_Morning,Mumbai,Economy,12.25,1,5949,Orta,0-10
19,19,AirAsia,I5-747,Delhi,Evening,one,Morning,Mumbai,Economy,16.33,1,5949,Uzun,0-10
20,20,GO_FIRST,G8-266,Delhi,Early_Morning,one,Evening,Mumbai,Economy,11.75,1,5954,Orta,0-10
21,21,GO_FIRST,G8-101,Delhi,Early_Morning,one,Night,Mumbai,Economy,14.50,1,5954,Orta,0-10
22,22,GO_FIRST,G8-103,Delhi,Evening,one,Morning,Mumbai,Economy,15.67,1,5954,Uzun,0-10
23,23,Air_India,AI-441,Delhi,Evening,one,Night,Mumbai,Economy,3.75,1,5955,Qısa,0-10
24,24,Indigo,6E-5328,Delhi,Morning,zero,Morning,Mumbai,Economy,2.50,1,6165,Qısa,0-10
25,25,Vistara,UK-933,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6690,Qısa,0-10
26,26,Indigo,6E-2046,Delhi,Evening,zero,Evening,Mumbai,Economy,2.17,1,6585,Qısa,0-10
27,27,AirAsia,I5-744,Delhi,Morning,one,Afternoon,Mumbai,Economy,5.83,1,8869,Orta,0-10
28,28,SpiceJet,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,10260,Qısa,0-10
29,29,Indigo,6E-5041,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,10470,Qısa,0-10

Ən çox uçuş olan mənbə şəhər və orta qiymət göstərilir.

In [97]:
df['source_city']

0           Delhi
1           Delhi
2           Delhi
3           Delhi
4           Delhi
           ...
300148    Chennai
300149    Chennai
300150    Chennai
300151    Chennai
300152    Chennai
Name: source_city, Length: 300153, dtype: str

In [11]:
df['source_city'].value_counts().idxmax()

'Delhi'

In [19]:
df.groupby(('source_city')).agg({'price' : 'mean'})

                    price
source_city
Bangalore    21469.460575
Chennai      21995.339871
Delhi        18951.326639
Hyderabad    20155.623879
Kolkata      21746.235679
Mumbai       21483.818839

Siniflərin uçuş sayı və orta qiyməti arasındakı fərqi görürük.

In [9]:
df['class'].value_counts()

class
Economy     206666
Business     93487
Name: count, dtype: int64

In [13]:
df.groupby('class')['price'].mean()

class
Business    52540.081124
Economy      6572.342383
Name: price, dtype: float64

In [21]:
df.pivot_table(values='days_left', index='class', aggfunc='mean')

          days_left
class
Business  25.741857
Economy   26.123673

Burada ən bahalı ilə ən ucuz aviaşirkətlərin və onlara uyğun ən bahalı və ən ucuz şəhərləri görürük.

In [4]:
df.groupby(['airline','source_city'])['price'].mean().sort_values(ascending=False)

airline    source_city
Vistara    Kolkata        32794.276565
           Mumbai         31522.101390
           Bangalore      30834.436629
           Chennai        30401.842703
           Delhi          28938.500342
           Hyderabad      27791.447325
Air_India  Chennai        25415.500908
           Kolkata        25233.867742
           Bangalore      24874.431796
           Mumbai         22540.778419
           Hyderabad      22458.063853
           Delhi          21899.890758
SpiceJet   Kolkata         6852.890601
GO_FIRST   Kolkata         6638.820334
Indigo     Kolkata         6223.829221
SpiceJet   Hyderabad       6189.731928
           Bangalore       6184.534661
           Mumbai          6101.956747
           Delhi           6084.649762
GO_FIRST   Delhi           5742.409679
           Bangalore       5492.290574
           Mumbai          5421.236351
           Chennai         5403.972847
SpiceJet   Chennai         5401.044299
Indigo     Delhi           5386.570134
           Mumbai          5371.185985
           Bangalore       5230.785311
GO_FIRST   Hyderabad       4958.293131
Indigo     Chennai         4827.233916
           Hyderabad       4774.240708
AirAsia    Delhi           4514.854798
           Kolkata         4504.940615
           Bangalore       4222.787158
           Mumbai          3698.312960
           Hyderabad       3359.273319
           Chennai         3243.964619
Name: price, dtype: float64